import {NumericFrameState} from './Railroad';

export enum FrameTypes {
    BALDWIN622D = '622D',
    BOXCAR = 'boxcar',
    CABOOSE = 'caboose',
    CLASS70 = 'class70',
    CLASS70_TENDER = 'class70_tender',
    CLIMAX = 'climax',
    COOKE260 = 'cooke260',
    COOKE260_TENDER = 'cooke260_tender',
    COOKE280 = 'cooke280',
    COOKE280_TENDER = 'cooke280_tender',
    EUREKA = 'eureka',
    EUREKA_TENDER = 'eureka_tender',
    FLATCAR_CORDWOOD = 'flatcar_cordwood',
    FLATCAR_LOGS = 'flatcar_logs',
    FLATCAR_STAKES = 'flatcar_stakes',
    GLENBROOK = 'glenbrook',
    GLENBROOK_TENDER = 'glenbrook_tender',
    HANDCAR = 'handcar',
    HEISLER = 'heisler',
    HOPPER = 'flatcar_hopper',
    MONTEZUMA = 'montezuma',
    MONTEZUMA_TENDER = 'montezuma_tender',
    MOSCA = 'mosca',
    MOSCA_TENDER = 'mosca_tender',
    PLOW = 'plow',
    PORTER040 = 'porter_040',
    PORTER042 = 'porter_042',
    SHAY = 'shay',
    TANKER = 'flatcar_tanker',
    WAYCAR = 'waycar',
}

export interface FrameDefinition {
    engine: boolean;
    freight: boolean;
    length: number;
    name: string;
    name_length: number;
    name_lines: number;
    number_length: number;
    number_lines: number;
    tender: boolean;
    min?: Partial<Record<keyof NumericFrameState, number>>;
    max?: Partial<Record<keyof NumericFrameState, number>>;
}

export const frameDefinitions: Record<string, FrameDefinition> = {
    [FrameTypes.BALDWIN622D]: {
        engine: true,
        freight: false,
        length: 760.0,
        name: 'D&RGW Class 48',
        name_length: 20,
        name_lines: 3,
        number_length: 4,
        number_lines: 1,
        tender: false,
        min: {
            headlightType: 1,
            paintType: 1,
            reverserValue: -1,
            smokestackType: 1,
        },
        max: {
            boilerFireTemp: 400,
            boilerFuelAmount: 70,
            boilerPressure: 130,
            boilerWaterLevel: 5000,
            boilerWaterTemp: 110,
            brakeValue: 1,
            headlightType: 2,
            paintType: 1,
            regulatorValue: 1,
            reverserValue: 1,
            sanderAmount: 100,
            smokestackType: 3,
            tenderFuelAmount: 144,
            tenderWaterAmount: 1600,
        },
    },
    [FrameTypes.BOXCAR]: {
        engine: false,
        freight: true,
        length: 822.82,
        name: 'Boxcar',
        name_length: 13,
        name_lines: 4,
        number_length: 7,
        number_lines: 4,
        tender: false,
        min: {
            headlightType: 1,
            paintType: 1,
            smokestackType: 1,
        },
        max: {
            brakeValue: 1,
            headlightType: 1,
            paintType: 7,
            smokestackType: 1,
        },
    },
    [FrameTypes.CABOOSE]: {
        engine: false,
        freight: false,
        length: 679.0,
        name: 'Bobber Caboose',
        name_length: 20,
        name_lines: 1,
        number_length: 12,
        number_lines: 1,
        tender: false,
        min: {
            headlightType: 1,
            paintType: 1,
            smokestackType: 1,
        },
        max: {
            boilerFireTemp: 400,
            boilerFuelAmount: 50,
            boilerPressure: 120,
            boilerWaterLevel: 500,
            boilerWaterTemp: 110,
            brakeValue: 1,
            headlightType: 1,
            markerLightsCenterState: 3,
            markerLightsFrontLeftState: 3,
            markerLightsFrontRightState: 3,
            markerLightsRearLeftState: 3,
            markerLightsRearRightState: 3,
            paintType: 10,
            smokestackType: 1,
            tenderFuelAmount: 15,
        },
    },
    [FrameTypes.CLASS70]: {
        engine: true,
        tender: false,
        freight: false,
        name: 'D&RG Class 70',
        length: 938.9,
        name_length: 14,
        name_lines: 1,
        number_length: 3,
        number_lines: 1,
        min: {
            headlightType: 1,
            paintType: 1,
            reverserValue: -1,
            smokestackType: 1,
        },
        max: {
            boilerFireTemp: 400,
            boilerFuelAmount: 100,
            boilerPressure: 130,
            boilerWaterLevel: 6000,
            boilerWaterTemp: 110,
            brakeValue: 1,
            compressorAirPressure: 100,
            compressorValveValue: 1,
            markerLightsFrontLeftState: 3,
            markerLightsFrontRightState: 3,
            paintType: 3,
            regulatorValue: 1,
            reverserValue: 1,
            headlightType: 3,
            sanderAmount: 100,
            smokestackType: 3,
        },
    },
    [FrameTypes.CLASS70_TENDER]: {
        engine: false,
        freight: false,
        length: 678.81,
        name: 'Class 70 Tender',
        name_length: 22,
        name_lines: 3,
        number_length: 0,
        number_lines: 0,
        tender: true,
        min: {
            headlightType: 1,
            paintType: 1,
            smokestackType: 1,
        },
        max: {
            brakeValue: 1,
            headlightType: 1,
            markerLightsRearLeftState: 3,
            markerLightsRearRightState: 3,
            paintType: 3,
            smokestackType: 1,
            tenderFuelAmount: 1350,
            tenderWaterAmount: 9500,
        },
    },
    [FrameTypes.CLIMAX]: {
        engine: true,
        freight: false,
        length: 849.89,
        name: 'Climax',
        name_length: 11,
        name_lines: 7,
        number_length: 2,
        number_lines: 1,
        tender: false,
        min: {
            headlightType: 1,
            paintType: 1,
            reverserValue: -1,
            smokestackType: 1,
        },
        max: {
            boilerFireTemp: 400,
            boilerFuelAmount: 80,
            boilerPressure: 160,
            boilerWaterLevel: 4000,
            boilerWaterTemp: 110,
            brakeValue: 1,
            compressorAirPressure: 100,
            compressorValveValue: 1,
            generatorValveValue: 1,
            paintType: 1,
            regulatorValue: 1,
            reverserValue: 1,
            headlightType: 1,
            sanderAmount: 100,
            smokestackType: 3,
            tenderFuelAmount: 332,
            tenderWaterAmount: 3000,
        },
    },
    [FrameTypes.COOKE260]: {
        engine: true,
        freight: false,
        length: 837.83,
        name: 'Cooke Mogul',
        name_length: 12,
        name_lines: 1,
        number_length: 3,
        number_lines: 1,
        tender: false,
        min: {
            headlightType: 1,
            paintType: 1,
            reverserValue: -1,
            smokestackType: 1,
        },
        max: {
            boilerFireTemp: 400,
            boilerFuelAmount: 80,
            boilerPressure: 150,
            boilerWaterLevel: 5000,
            boilerWaterTemp: 110,
            brakeValue: 1,
            compressorAirPressure: 100,
            compressorValveValue: 1,
            headlightType: 2,
            paintType: 1,
            regulatorValue: 1,
            reverserValue: 1,
            sanderAmount: 100,
            smokestackType: 3,
        },
    },
    [FrameTypes.COOKE260_TENDER]: {
        engine: false,
        freight: false,
        length: 641.73,
        name: 'Cooke Mogul Tender',
        name_length: 11,
        name_lines: 1,
        number_length: 6,
        number_lines: 1,
        tender: true,
        min: {
            headlightType: 1,
            paintType: 1,
            smokestackType: 1,
        },
        max: {
            brakeValue: 1,
            headlightType: 2,
            markerLightsRearLeftState: 3,
            markerLightsRearRightState: 3,
            paintType: 1,
            tenderFuelAmount: 1460,
            tenderWaterAmount: 9500,
            smokestackType: 1,
        },
    },
    [FrameTypes.COOKE280]: {
        engine: true,
        tender: false,
        freight: false,
        name: 'Cooke Consolidation',
        length: 870.0,
        name_length: 12,
        name_lines: 1,
        number_length: 3,
        number_lines: 1,
        min: {
            headlightType: 1,
            paintType: 1,
            reverserValue: -1,
            smokestackType: 1,
        },
        max: {
            boilerFireTemp: 400,
            boilerFuelAmount: 70,
            boilerPressure: 130,
            boilerWaterLevel: 5000,
            boilerWaterTemp: 110,
            brakeValue: 1,
            compressorAirPressure: 100,
            compressorValveValue: 1,
            headlightType: 3,
            markerLightsFrontLeftState: 3,
            markerLightsFrontRightState: 3,
            paintType: 5,
            regulatorValue: 1,
            reverserValue: 1,
            sanderAmount: 100,
            smokestackType: 4,
        },
    },
    [FrameTypes.COOKE280_TENDER]: {
        engine: false,
        tender: true,
        freight: false,
        name: 'Cooke Consolidation Tender',
        length: 625.0,
        name_length: 11,
        name_lines: 1,
        number_length: 6,
        number_lines: 1,
        min: {
            headlightType: 1,
            paintType: 1,
            smokestackType: 1,
        },
        max: {
            brakeValue: 1,
            headlightType: 3,
            markerLightsRearLeftState: 3,
            markerLightsRearRightState: 3,
            paintType: 5,
            smokestackType: 1,
            tenderFuelAmount: 1428,
            tenderWaterAmount: 9500,
        },
    },
    [FrameTypes.EUREKA]: {
        engine: true,
        freight: false,
        length: 802.13,
        name: 'Eureka',
        name_length: 8,
        name_lines: 1,
        number_length: 2,
        number_lines: 1,
        tender: false,
        min: {
            headlightType: 1,
            paintType: 1,
            reverserValue: -1,
            smokestackType: 1,
        },
        max: {
            boilerFireTemp: 400,
            boilerFuelAmount: 70,
            boilerPressure: 130,
            boilerWaterLevel: 5000,
            boilerWaterTemp: 110,
            brakeValue: 1,
            compressorAirPressure: 100,
            compressorValveValue: 1,
            headlightType: 3,
            paintType: 1,
            regulatorValue: 1,
            reverserValue: 1,
            sanderAmount: 100,
            smokestackType: 1,
        },
    },
    [FrameTypes.EUREKA_TENDER]: {
        engine: false,
        freight: false,
        length: 497.08,
        name: 'Eureka Tender',
        name_length: 18,
        name_lines: 1,
        number_length: 0,
        number_lines: 0,
        tender: true,
        min: {
            headlightType: 1,
            paintType: 1,
            smokestackType: 1,
        },
        max: {
            brakeValue: 1,
            headlightType: 1,
            markerLightsRearLeftState: 3,
            markerLightsRearRightState: 3,
            paintType: 1,
            smokestackType: 1,
            tenderFuelAmount: 499,
            tenderWaterAmount: 3800,
        },
    },
    [FrameTypes.FLATCAR_CORDWOOD]: {
        engine: false,
        freight: true,
        length: 785.6,
        name: 'Flatcar Tier 3',
        name_length: 8,
        name_lines: 1,
        number_length: 8,
        number_lines: 1,
        tender: false,
        min: {
            headlightType: 1,
            paintType: 1,
            smokestackType: 1,
        },
        max: {
            brakeValue: 1,
            headlightType: 1,
            paintType: 7,
            smokestackType: 1,
        },
    },
    [FrameTypes.FLATCAR_LOGS]: {
        engine: false,
        freight: true,
        length: 785.6,
        name: 'Flatcar Tier 1',
        name_length: 7,
        name_lines: 1,
        number_length: 12,
        number_lines: 1,
        tender: false,
        min: {
            headlightType: 1,
            paintType: 1,
            smokestackType: 1,
        },
        max: {
            brakeValue: 1,
            headlightType: 1,
            paintType: 7,
            smokestackType: 1,
        },
    },
    [FrameTypes.FLATCAR_STAKES]: {
        engine: false,
        freight: true,
        length: 785.6,
        name: 'Flatcar Tier 2',
        name_length: 8,
        name_lines: 1,
        number_length: 8,
        number_lines: 1,
        tender: false,
        min: {
            headlightType: 1,
            paintType: 1,
            smokestackType: 1,
        },
        max: {
            brakeValue: 1,
            headlightType: 1,
            paintType: 7,
            smokestackType: 1,
        },
    },
    [FrameTypes.GLENBROOK]: {
        engine: true,
        freight: false,
        length: 837.83,
        name: 'Glenbrook',
        name_length: 12,
        name_lines: 1,
        number_length: 3,
        number_lines: 1,
        tender: false,
        min: {
            headlightType: 1,
            paintType: 1,
            reverserValue: -1,
            smokestackType: 1,
        },
        max: {
            boilerFireTemp: 400,
            boilerFuelAmount: 70,
            boilerPressure: 130,
            boilerWaterLevel: 5000,
            boilerWaterTemp: 110,
            brakeValue: 1,
            compressorAirPressure: 100,
            compressorValveValue: 1,
            headlightType: 3,
            paintType: 6,
            regulatorValue: 1,
            reverserValue: 1,
            sanderAmount: 100,
            smokestackType: 5,
        },
    },
    [FrameTypes.GLENBROOK_TENDER]: {
        engine: false,
        freight: false,
        length: 505.0,
        name: 'Glenbrook Tender',
        name_length: 11,
        name_lines: 1,
        number_length: 6,
        number_lines: 1,
        tender: true,
        min: {
            headlightType: 1,
            paintType: 1,
            smokestackType: 1,
        },
        max: {
            brakeValue: 1,
            headlightType: 1,
            paintType: 6,
            smokestackType: 1,
            tenderFuelAmount: 798,
            tenderWaterAmount: 3800,
        },
    },
    [FrameTypes.HANDCAR]: {
        engine: true,
        freight: false,
        length: 220.2,
        name: 'Handcar',
        name_length: 18,
        name_lines: 1,
        number_length: 5,
        number_lines: 1,
        tender: false,
        min: {
            headlightType: 1,
            paintType: 1,
            reverserValue: -1,
            smokestackType: 1,
        },
        max: {
            boilerPressure: 120,
            boilerWaterLevel: 100,
            boilerWaterTemp: 10,
            brakeValue: 1,
            headlightType: 1,
            paintType: 1,
            regulatorValue: 1,
            reverserValue: 1,
            smokestackType: 1,
            tenderFuelAmount: 20,
        },
    },
    [FrameTypes.HEISLER]: {
        engine: true,
        freight: false,
        length: 913.73,
        name: 'Heisler',
        name_length: 11,
        name_lines: 6,
        number_length: 2,
        number_lines: 1,
        tender: false,
        min: {
            headlightType: 1,
            paintType: 1,
            reverserValue: -1,
            smokestackType: 1,
        },
        max: {
            boilerFireTemp: 400,
            boilerFuelAmount: 80,
            boilerPressure: 160,
            boilerWaterLevel: 5000,
            boilerWaterTemp: 110,
            brakeValue: 1,
            compressorAirPressure: 100,
            compressorValveValue: 1,
            headlightType: 3,
            paintType: 1,
            regulatorValue: 1,
            reverserValue: 1,
            sanderAmount: 100,
            smokestackType: 3,
            tenderFuelAmount: 454,
            tenderWaterAmount: 3000,
        },
    },
    [FrameTypes.HOPPER]: {
        engine: false,
        freight: true,
        length: 785.6,
        name: 'Hopper',
        name_length: 7,
        name_lines: 1,
        number_length: 4,
        number_lines: 1,
        tender: false,
        min: {
            headlightType: 1,
            paintType: 1,
            smokestackType: 1,
        },
        max: {
            brakeValue: 1,
            headlightType: 1,
            paintType: 1,
            smokestackType: 1,
        },
    },
    [FrameTypes.MONTEZUMA]: {
        engine: true,
        freight: false,
        length: 680.0,
        name: 'Montezuma',
        name_length: 12,
        name_lines: 1,
        number_length: 3,
        number_lines: 1,
        tender: false,
        min: {
            headlightType: 1,
            paintType: 1,
            reverserValue: -1,
            smokestackType: 1,
        },
        max: {
            boilerFireTemp: 400,
            boilerFuelAmount: 70,
            boilerPressure: 130,
            boilerWaterLevel: 5000,
            boilerWaterTemp: 110,
            brakeValue: 1,
            headlightType: 2,
            paintType: 2,
            regulatorValue: 1,
            reverserValue: 1,
            sanderAmount: 100,
            smokestackType: 3,
        },
    },
    [FrameTypes.MONTEZUMA_TENDER]: {
        engine: false,
        freight: false,
        length: 420.0,
        name: 'Montezuma Tender',
        name_length: 11,
        name_lines: 1,
        number_length: 6,
        number_lines: 1,
        tender: true,
        min: {
            headlightType: 1,
            paintType: 1,
            smokestackType: 1,
        },
        max: {
            brakeValue: 1,
            headlightType: 2,
            paintType: 2,
            smokestackType: 1,
            tenderFuelAmount: 470,
            tenderWaterAmount: 5900,
        },
    },
    [FrameTypes.MOSCA]: {
        engine: true,
        freight: false,
        length: 873.0,
        name: 'Mosca',
        name_length: 12,
        name_lines: 1,
        number_length: 3,
        number_lines: 1,
        tender: false,
        min: {
            headlightType: 1,
            paintType: 1,
            reverserValue: -1,
            smokestackType: 1,
        },
        max: {
            boilerFireTemp: 400,
            boilerFuelAmount: 70,
            boilerPressure: 130,
            boilerWaterLevel: 5000,
            boilerWaterTemp: 110,
            brakeValue: 1,
            headlightType: 3,
            paintType: 1,
            regulatorValue: 1,
            reverserValue: 1,
            sanderAmount: 100,
            smokestackType: 5,
        },
    },
    [FrameTypes.MOSCA_TENDER]: {
        engine: false,
        freight: false,
        length: 530.0,
        name: 'Mosca Tender',
        name_length: 11,
        name_lines: 1,
        number_length: 6,
        number_lines: 1,
        tender: true,
        min: {
            headlightType: 1,
            paintType: 1,
            smokestackType: 1,
        },
        max: {
            brakeValue: 1,
            headlightType: 3,
            paintType: 1,
            smokestackType: 1,
            tenderFuelAmount: 854,
            tenderWaterAmount: 3800,
        },
    },
    [FrameTypes.PLOW]: {
        engine: false,
        freight: false,
        length: 610.0,
        name: 'Snow Plow',
        name_length: 10,
        name_lines: 2,
        number_length: 4,
        number_lines: 1,
        tender: false,
        min: {
            headlightType: 1,
            paintType: 1,
            smokestackType: 1,
        },
        max: {
            brakeValue: 1,
            headlightType: 1,
            markerLightsFrontLeftState: 3,
            markerLightsFrontRightState: 3,
            paintType: 4,
            smokestackType: 1,
        },
    },
    [FrameTypes.PORTER040]: {
        engine: true,
        freight: false,
        length: 391.2,
        name: 'Porter',
        name_length: 12,
        name_lines: 1,
        number_length: 2,
        number_lines: 1,
        tender: false,
        min: {
            headlightType: 1,
            paintType: 1,
            reverserValue: -1,
            smokestackType: 1,
        },
        max: {
            boilerFireTemp: 400,
            boilerFuelAmount: 50,
            boilerPressure: 120,
            boilerWaterLevel: 500,
            boilerWaterTemp: 110,
            brakeValue: 1,
            headlightType: 2,
            paintType: 1,
            regulatorValue: 1,
            reverserValue: 1,
            sanderAmount: 100,
            smokestackType: 1,
            tenderFuelAmount: 66,
            tenderWaterAmount: 800,
        },
    },
    [FrameTypes.PORTER042]: {
        engine: true,
        freight: false,
        length: 461.35,
        name: 'Porter 2',
        name_length: 12,
        name_lines: 1,
        number_length: 2,
        number_lines: 1,
        min: {
            paintType: 1,
            reverserValue: -1,
        },
        max: {
            boilerFireTemp: 400,
            boilerFuelAmount: 50,
            boilerPressure: 120,
            boilerWaterLevel: 500,
            boilerWaterTemp: 110,
            brakeValue: 1,
            headlightType: 2,
            paintType: 1,
            regulatorValue: 1,
            reverserValue: 1,
            sanderAmount: 100,
            smokestackType: 1,
            tenderFuelAmount: 164,
            tenderWaterAmount: 800,
        },
        tender: false,
    },
    [FrameTypes.SHAY]: {
        engine: true,
        freight: false,
        length: 800.0,
        name: 'Shay',
        name_length: 12,
        name_lines: 1,
        number_length: 2,
        number_lines: 1,
        tender: false,
        min: {
            headlightType: 1,
            paintType: 1,
            reverserValue: -1,
            smokestackType: 1,
        },
        max: {
            boilerFireTemp: 400,
            boilerFuelAmount: 80,
            boilerPressure: 160,
            boilerWaterLevel: 4000,
            boilerWaterTemp: 110,
            brakeValue: 1,
            headlightType: 3,
            paintType: 3,
            regulatorValue: 1,
            reverserValue: 1,
            sanderAmount: 100,
            smokestackType: 4,
            tenderFuelAmount: 317,
            tenderWaterAmount: 3000,
        },
    },
    [FrameTypes.TANKER]: {
        engine: false,
        freight: true,
        length: 785.6,
        name: 'Tanker',
        name_length: 19,
        name_lines: 1,
        number_length: 12,
        number_lines: 1,
        tender: false,
        min: {
            headlightType: 1,
            paintType: 1,
            smokestackType: 1,
        },
        max: {
            brakeValue: 1,
            headlightType: 1,
            paintType: 10,
            smokestackType: 1,
        },
    },
    [FrameTypes.WAYCAR]: {
        engine: false,
        freight: false,
        length: 615.0,
        name: 'DSP&P Waycar',
        name_length: 21,
        name_lines: 1,
        number_length: 12,
        number_lines: 1,
        tender: false,
        min: {
            headlightType: 1,
            paintType: 1,
            smokestackType: 1,
        },
        max: {
            boilerFireTemp: 400,
            boilerFuelAmount: 50,
            boilerPressure: 120,
            boilerWaterLevel: 500,
            boilerWaterTemp: 110,
            brakeValue: 1,
            headlightType: 1,
            markerLightsFrontLeftState: 3,
            markerLightsFrontRightState: 3,
            markerLightsRearLeftState: 3,
            markerLightsRearRightState: 3,
            paintType: 13,
            smokestackType: 1,
            tenderFuelAmount: 25,
        },
    },
};

interface FrameStateMetadata {
    name: string;
    type?: ('slider' | string[]);
    unit?: string;
    step?: number;
}

export const frameStateMetadata: Record<keyof NumericFrameState, FrameStateMetadata> = {
    boilerFireTemp: {
        name: 'Boiler Fire Temperature',
        type: 'slider',
        unit: 'C',
    },
    boilerFuelAmount: {
        name: 'Boiler Fuel',
        type: 'slider',
    },
    boilerPressure: {
        name: 'Boiler Pressure',
        type: 'slider',
        unit: 'psi',
    },
    boilerWaterLevel: {
        name: 'Boiler Water',
        type: 'slider',
        unit: 'L',
    },
    boilerWaterTemp: {
        name: 'Boiler Water Temperature',
        type: 'slider',
        unit: 'C',
    },
    brakeValue: {
        name: 'Brake',
        type: 'slider',
        step: 0.01,
    },
    compressorAirPressure: {
        name: 'Compressor Air Pressure',
        type: 'slider',
        unit: 'psi',
    },
    compressorValveValue: {
        name: 'Compressor',
        type: 'slider',
        step: 0.01,
    },
    generatorValveValue: {
        name: 'Generator',
        type: 'slider',
        step: 0.01,
    },
    headlightType: {
        name: 'Headlight',
    },
    markerLightsCenterState: {
        name: 'Marker Lights Center',
        type: ['None', 'Green', 'Red', 'White'],
    },
    markerLightsFrontLeftState: {
        name: 'Marker Lights Front Left',
        type: ['None', 'Green', 'Red', 'White'],
    },
    markerLightsFrontRightState: {
        name: 'Marker Lights Front Right',
        type: ['None', 'Green', 'Red', 'White'],
    },
    markerLightsRearLeftState: {
        name: 'Marker Lights Rear Left',
        type: ['None', 'Green', 'Red', 'White'],
    },
    markerLightsRearRightState: {
        name: 'Marker Lights Rear Right',
        type: ['None', 'Green', 'Red', 'White'],
    },
    paintType: {
        name: 'Paint',
    },
    regulatorValue: {
        name: 'Regulator',
        type: 'slider',
        step: 0.01,
    },
    reverserValue: {
        name: 'Reverser',
        type: 'slider',
        step: 0.01,
    },
    sanderAmount: {
        name: 'Sand',
        type: 'slider',
    },
    smokestackType: {
        name: 'Smokestack',
    },
    tenderFuelAmount: {
        name: 'Firewood',
        type: 'slider',
        unit: 'logs',
    },
    tenderWaterAmount: {
        name: 'Tank Water',
        type: 'slider',
        unit: 'L',
    },
};

export const cargoLimits: Record<string, Record<string, number>> = {
    boxcar: {
        crate_tools: 32,
    },
    flatcar_cordwood: {
        cordwood: 8,
        oilbarrel: 46,
    },
    flatcar_hopper: {
        coal: 10,
        ironore: 10,
    },
    flatcar_logs: {
        log: 6,
        steelpipe: 9,
    },
    flatcar_stakes: {
        beam: 3,
        lumber: 6,
        rail: 10,
        rawiron: 3,
    },
    flatcar_tanker: {
        crudeoil: 12,
    },
};
