import {HermiteCurve} from './util-bezier';

export enum SplineTrackType {
    BALLAST_H01 = 'ballast_h01',
    BALLAST_H01_SNOW = 'ballast_h01_snow',
    BALLAST_H05 = 'ballast_h05',
    BALLAST_H05_SNOW = 'ballast_h05_snow',
    BALLAST_H10 = 'ballast_h10',
    BALLAST_H10_SNOW = 'ballast_h10_snow',
    RAIL_914 = 'rail_914',
    RAIL_914_BRIDGE_TRUSS = 'rail_914_bridge_truss',
    RAIL_914_BUMPER = 'rail_914_bumper',
    RAIL_914_BUMPER_SNOW = 'rail_914_bumper_snow',
    RAIL_914_H01 = 'rail_914_h01',
    RAIL_914_H01_SNOW = 'rail_914_h01_snow',
    RAIL_914_H05 = 'rail_914_h05',
    RAIL_914_H05_SNOW = 'rail_914_h05_snow',
    RAIL_914_H10 = 'rail_914_h10',
    RAIL_914_H10_SNOW = 'rail_914_h10_snow',
    RAIL_914_SNOW = 'rail_914_snow',
    RAIL_914_SWITCH_3WAY_LEFT = 'rail_914_switch_3way_left',
    RAIL_914_SWITCH_3WAY_LEFT_NOBALLAST = 'rail_914_switch_3way_left_noballast',
    RAIL_914_SWITCH_3WAY_LEFT_NOBALLAST_SNOW = 'rail_914_switch_3way_left_noballast_snow',
    RAIL_914_SWITCH_3WAY_LEFT_SNOW = 'rail_914_switch_3way_left_snow',
    RAIL_914_SWITCH_3WAY_RIGHT = 'rail_914_switch_3way_right',
    RAIL_914_SWITCH_3WAY_RIGHT_NOBALLAST = 'rail_914_switch_3way_right_noballast',
    RAIL_914_SWITCH_3WAY_RIGHT_NOBALLAST_SNOW = 'rail_914_switch_3way_right_noballast_snow',
    RAIL_914_SWITCH_3WAY_RIGHT_SNOW = 'rail_914_switch_3way_right_snow',
    RAIL_914_SWITCH_CROSS_45 = 'rail_914_switch_cross_45',
    RAIL_914_SWITCH_CROSS_45_SNOW = 'rail_914_switch_cross_45_snow',
    RAIL_914_SWITCH_CROSS_90 = 'rail_914_switch_cross_90',
    RAIL_914_SWITCH_CROSS_90_SNOW = 'rail_914_switch_cross_90_snow',
    RAIL_914_SWITCH_LEFT = 'rail_914_switch_left',
    RAIL_914_SWITCH_LEFT_MIRROR = 'rail_914_switch_left_mirror',
    RAIL_914_SWITCH_LEFT_MIRROR_NOBALLAST = 'rail_914_switch_left_mirror_noballast',
    RAIL_914_SWITCH_LEFT_MIRROR_NOBALLAST_SNOW = 'rail_914_switch_left_mirror_noballast_snow',
    RAIL_914_SWITCH_LEFT_MIRROR_SNOW = 'rail_914_switch_left_mirror_snow',
    RAIL_914_SWITCH_LEFT_NOBALLAST = 'rail_914_switch_left_noballast',
    RAIL_914_SWITCH_LEFT_NOBALLAST_SNOW = 'rail_914_switch_left_noballast_snow',
    RAIL_914_SWITCH_LEFT_SNOW = 'rail_914_switch_left_snow',
    RAIL_914_SWITCH_RIGHT = 'rail_914_switch_right',
    RAIL_914_SWITCH_RIGHT_MIRROR = 'rail_914_switch_right_mirror',
    RAIL_914_SWITCH_RIGHT_MIRROR_NOBALLAST = 'rail_914_switch_right_mirror_noballast',
    RAIL_914_SWITCH_RIGHT_MIRROR_NOBALLAST_SNOW = 'rail_914_switch_right_mirror_noballast_snow',
    RAIL_914_SWITCH_RIGHT_MIRROR_SNOW = 'rail_914_switch_right_mirror_snow',
    RAIL_914_SWITCH_RIGHT_NOBALLAST = 'rail_914_switch_right_noballast',
    RAIL_914_SWITCH_RIGHT_NOBALLAST_SNOW = 'rail_914_switch_right_noballast_snow',
    RAIL_914_SWITCH_RIGHT_SNOW = 'rail_914_switch_right_snow',
    RAIL_914_TRESTLE_PILE_01 = 'rail_914_trestle_pile_01',
    RAIL_914_TRESTLE_STEEL_01 = 'rail_914_trestle_steel_01',
    RAIL_914_TRESTLE_WOOD_01 = 'rail_914_trestle_wood_01',
    RAIL_914_TUNNEL = 'rail_914_tunnel',
    RAIL_914_WALL_01 = 'rail_914_wall_01',
    RAIL_914_WALL_01_NORAIL = 'rail_914_wall_01_norail',
}

const secondLegSwitchLeft = {
    endPoint: {x: 1879.3, y: 0, z: 0},
    endTangent: {x: 1879.3, y: 0, z: 0},
    startPoint: {x: 0, y: 0, z: 0},
    startTangent: {x: 1879.3, y: 0, z: 0},
};

const secondLegSwitchRight = {
    endPoint: {x: 1863.4, y: 184.8, z: 0},
    endTangent: {x: 2125.36, y: 348.04, z: 0},
    startPoint: {x: 0, y: 0, z: 0},
    startTangent: {x: 2153.67, y: 0, z: 0},
};

const switchCross45 = {
    endPoint: {x: 512.1, y: -212.1, z: 0},
    endTangent: {x: 424.2, y: -424.2, z: 0},
    startPoint: {x: 87.9, y: 212.1, z: 0},
    startTangent: {x: 424.2, y: -424.2, z: 0},
};

const switchCross90 = {
    endPoint: {x: 191.2, y: 191.2, z: 0},
    endTangent: {x: 0, y: 382.4, z: 0},
    startPoint: {x: 191.2, y: -191.2, z: 0},
    startTangent: {x: 0, y: 382.4, z: 0},
};

export const switchExtraLegs: Partial<Record<SplineTrackType, HermiteCurve[]>> = {
    [SplineTrackType.RAIL_914_SWITCH_3WAY_LEFT]: [secondLegSwitchLeft, secondLegSwitchRight],
    [SplineTrackType.RAIL_914_SWITCH_3WAY_LEFT_NOBALLAST]: [secondLegSwitchLeft, secondLegSwitchRight],
    [SplineTrackType.RAIL_914_SWITCH_3WAY_LEFT_NOBALLAST_SNOW]: [secondLegSwitchLeft, secondLegSwitchRight],
    [SplineTrackType.RAIL_914_SWITCH_3WAY_LEFT_SNOW]: [secondLegSwitchLeft, secondLegSwitchRight],
    [SplineTrackType.RAIL_914_SWITCH_3WAY_RIGHT]: [secondLegSwitchLeft, secondLegSwitchRight],
    [SplineTrackType.RAIL_914_SWITCH_3WAY_RIGHT_NOBALLAST]: [secondLegSwitchLeft, secondLegSwitchRight],
    [SplineTrackType.RAIL_914_SWITCH_3WAY_RIGHT_NOBALLAST_SNOW]: [secondLegSwitchLeft, secondLegSwitchRight],
    [SplineTrackType.RAIL_914_SWITCH_3WAY_RIGHT_SNOW]: [secondLegSwitchLeft, secondLegSwitchRight],
    [SplineTrackType.RAIL_914_SWITCH_CROSS_45]: [switchCross45],
    [SplineTrackType.RAIL_914_SWITCH_CROSS_45_SNOW]: [switchCross45],
    [SplineTrackType.RAIL_914_SWITCH_CROSS_90]: [switchCross90],
    [SplineTrackType.RAIL_914_SWITCH_CROSS_90_SNOW]: [switchCross90],
    [SplineTrackType.RAIL_914_SWITCH_LEFT]: [secondLegSwitchLeft],
    [SplineTrackType.RAIL_914_SWITCH_LEFT_MIRROR]: [secondLegSwitchLeft],
    [SplineTrackType.RAIL_914_SWITCH_LEFT_MIRROR_NOBALLAST]: [secondLegSwitchLeft],
    [SplineTrackType.RAIL_914_SWITCH_LEFT_MIRROR_NOBALLAST_SNOW]: [secondLegSwitchLeft],
    [SplineTrackType.RAIL_914_SWITCH_LEFT_MIRROR_SNOW]: [secondLegSwitchLeft],
    [SplineTrackType.RAIL_914_SWITCH_LEFT_NOBALLAST]: [secondLegSwitchLeft],
    [SplineTrackType.RAIL_914_SWITCH_LEFT_NOBALLAST_SNOW]: [secondLegSwitchLeft],
    [SplineTrackType.RAIL_914_SWITCH_LEFT_SNOW]: [secondLegSwitchLeft],
    [SplineTrackType.RAIL_914_SWITCH_RIGHT]: [secondLegSwitchRight],
    [SplineTrackType.RAIL_914_SWITCH_RIGHT_MIRROR]: [secondLegSwitchRight],
    [SplineTrackType.RAIL_914_SWITCH_RIGHT_MIRROR_NOBALLAST]: [secondLegSwitchRight],
    [SplineTrackType.RAIL_914_SWITCH_RIGHT_MIRROR_NOBALLAST_SNOW]: [secondLegSwitchRight],
    [SplineTrackType.RAIL_914_SWITCH_RIGHT_MIRROR_SNOW]: [secondLegSwitchRight],
    [SplineTrackType.RAIL_914_SWITCH_RIGHT_NOBALLAST]: [secondLegSwitchRight],
    [SplineTrackType.RAIL_914_SWITCH_RIGHT_NOBALLAST_SNOW]: [secondLegSwitchRight],
    [SplineTrackType.RAIL_914_SWITCH_RIGHT_SNOW]: [secondLegSwitchRight],
};
