name: Build with Webpack

on:
  pull_request:
    branches:
      - mainline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: 'npm'
      - run: npm ci
      - run: npm run check
      - run: npx webpack --mode=development
